version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=prod
      - PORT=4000
      - RATE_LIMIT=100  # Default to 100 requests per hour
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    # Uncomment the following lines if you need to mount volumes for development
    # volumes:
    #   - ./config:/app/config
    #   - ./lib:/app/lib
    #   - ./priv:/app/priv 